image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - connorshea.vscode-ruby-test-adapter@0.6.1:HO9rpcRv7bmRIuo7Mty/zg==
    - hbenl.vscode-test-explorer@2.15.0:koqDUMWDPJzELp/hdS/lWw==

ports:
  - port: 3000
    onOpen: open-preview
    
tasks:
  - init: bundle install && yarn install --check-files
    command: rails server